package org.example.backendai.mapper;

import org.example.backendai.dto.request.MedicalEncounterRequest;
import org.example.backendai.dto.response.MedicalEncounterResponse;
import org.example.backendai.entity.MedicalEncounter;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Mappings;

@Mapper(componentModel = "spring")
public interface MedicalEncounterMapper {

    // Map from Request to Entity
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "patient", ignore = true)
    @Mapping(target = "severityLevel", ignore = true)
    MedicalEncounter toMedicalEncounter(MedicalEncounterRequest request);

    // Map from AI Response (MedicalEncounterResponse) to Entity
    // The AI response has all the medical data that needs to be stored
    @Mapping(target = "id", ignore = true) // ID will be generated by database
    @Mapping(target = "patient", ignore = true) // Patient will be set manually in service
    MedicalEncounter toMedicalEncounterFromAIResponse(MedicalEncounterResponse aiResponse);

    // Map from Entity to Response
    @Mappings({
            @Mapping(source = "medicalEncounter.id", target = "id"),
            @Mapping(source = "medicalEncounter.patient.id", target = "patientId"),
            @Mapping(
                    target = "patientName",
                    expression = "java(medicalEncounter.getPatient() != null && medicalEncounter.getPatient().getUser() != null ? medicalEncounter.getPatient().getUser().getFullName() : null)"
            )
    })
    MedicalEncounterResponse toMedicalEncounterResponse(MedicalEncounter medicalEncounter);
}